
markdown: kramdown

# set the base URL to root
baseurl: 

# pretty URLs
permalink: /:year/:month/:day/:title/

# exclude some irrelevant folders and files
exclude: [ 'src', 'README.md', 'node_modules', '.sass-cache', 'Gruntfile.js', 'package.json', '*.log' ]


# social network links
social_twitter: https://twitter.com/jamespederson
social_github: https://github.com/jpederson/
social_facebook: https://fb.me/james.pederson
social_linkedin: https://www.linkedin.com/in/jamespederson/
social_instagram: https://instagram.com/james.pederson


# phone
phone: '+16084437567'


# admin email
email: james@jpederson.com
