
markdown: kramdown

# set the base URL to root
baseurl: 

# pretty URLs
permalink: /:year/:month/:day/:title/

# set up a port number for the local server
port: 4000;

# exclude some irrelevant folders and files
exclude: [ 'src', 'README.md', 'node_modules', '.sass-cache', 'Gruntfile.js', 'package.json', '*.log' ]


# social network links
social_twitter: http://twitter.com/jamespederson
social_github: https://github.com/jpederson/
social_facebook: https://facebook.com/james.pederson
social_linkedin: http://www.linkedin.com/in/jamespederson/
social_google: https://plus.google.com/u/0/+JamesPederson85/posts

# admin email
email: james@jpederson.com
